"""Writer node.

Turns the Analyst's structured ``Analysis`` into a clean markdown report with
the required sections: Executive Summary, Financial Highlights, Risk Factors,
Recent News & Sentiment, Conclusion. Falls back to deterministic rendering of
the analysis dict if the LLM is unavailable.
"""
from __future__ import annotations

import json
import logging
from typing import Any

from backend.graph.state import ResearchState
from backend.llm import get_chat_model

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = (
    "You are a financial writer. Convert the provided structured analysis into a "
    "polished, professional equity research note in GitHub-flavored Markdown. "
    "Use EXACTLY these second-level sections in this order:\n"
    "## Executive Summary\n## Financial Highlights\n## Risk Factors\n"
    "## Recent News & Sentiment\n## Conclusion\n\n"
    "Guidelines: open with an H1 title '# {Company} ({TICKER}) — Equity Research'. "
    "Be concise and balanced, use bullet lists and a markdown table for financial "
    "highlights where helpful, and cite figures from the data. Do not invent data. "
    "End with a brief disclaimer that this is AI-generated and not investment advice. "
    "Output only the markdown, no preamble."
)


def _disclaimer() -> str:
    return (
        "\n\n---\n_This report was generated by an AI research agent for "
        "informational purposes only and is not investment advice._"
    )


def _sources_block(state: ResearchState) -> str:
    mda = state.get("mda", {})
    news = state.get("news", {})
    lines: list[str] = []
    if mda.get("source_url"):
        label = f"SEC {mda.get('form', 'filing')} ({mda.get('filing_date', 'n/a')})"
        lines.append(f"- {label}: {mda['source_url']}")
    for item in (news.get("results") or [])[:5]:
        if item.get("url"):
            lines.append(f"- {item.get('title', 'News')}: {item['url']}")
    return "\n".join(lines)


def _render_fallback(state: ResearchState) -> str:
    """Build markdown directly from the analysis dict (no LLM)."""
    company = state.get("company_name", state["ticker"])
    ticker = state["ticker"].upper()
    a = state.get("analysis", {}) or {}
    sent = a.get("recent_sentiment", {}) or {}
    fin = a.get("financial_summary", {}) or {}

    def bullets(items: list[str]) -> str:
        return "\n".join(f"- {i}" for i in (items or [])) or "- n/a"

    md = [
        f"# {company} ({ticker}) — Equity Research",
        "\n## Executive Summary",
        "**Bull case**",
        bullets(a.get("bull_case", [])),
        "\n**Bear case**",
        bullets(a.get("bear_case", [])),
        "\n## Financial Highlights",
        f"- P/E (trailing): {fin.get('pe_ratio', 'n/a')}",
        f"- Debt/Equity: {fin.get('debt_to_equity', 'n/a')}",
        f"- Free cash flow: {fin.get('free_cash_flow', 'n/a')}",
        f"- Revenue trend: {fin.get('revenue_trend', 'n/a')}",
        f"- Net income trend: {fin.get('net_income_trend', 'n/a')}",
        f"\n{fin.get('commentary', '')}",
        "\n## Risk Factors",
        bullets(a.get("key_risks", [])),
        "\n## Recent News & Sentiment",
        f"**Overall sentiment:** {sent.get('label', 'n/a')}",
        f"\n{sent.get('summary', '')}",
        bullets(sent.get("notable_headlines", [])),
        "\n## Conclusion",
        fin.get("commentary", "See analysis above."),
    ]
    sources = _sources_block(state)
    if sources:
        md.append("\n## Sources\n" + sources)
    return "\n".join(md) + _disclaimer()


def writer_node(state: ResearchState) -> dict[str, Any]:
    ticker = state["ticker"].strip().upper()
    company = state.get("company_name", ticker)
    logger.info("Writer: rendering report for %s", ticker)

    analysis = state.get("analysis", {})
    sources = _sources_block(state)

    user_content = (
        f"Company: {company}\nTicker: {ticker}\n\n"
        f"Structured analysis (JSON):\n{json.dumps(analysis, indent=2, default=str)}\n\n"
        f"Sources to cite (add a '## Sources' section if non-empty):\n{sources or 'none'}"
    )

    try:
        model = get_chat_model(temperature=0.3)
        response = model.invoke(
            [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ]
        )
        report = (response.content or "").strip()
        if not report:
            raise ValueError("empty completion")
        if "not investment advice" not in report.lower():
            report += _disclaimer()
        return {"report_markdown": report}
    except Exception as exc:  # noqa: BLE001
        logger.warning("Writer LLM call failed for %s: %s", ticker, exc)
        return {
            "report_markdown": _render_fallback(state),
            "errors": [f"Writer: LLM rendering failed ({exc}); used fallback template."],
        }
